services:
  - type: web
    name: labour-marketplace-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://beaconbd000_db_user:labour6258@cluster0.c75rz7i.mongodb.net/labour_db?retryWrites=true&w=majority
      - key: PORT
        value: 10000
